import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus, ClipboardList, Eye } from 'lucide-react';
import { participantsAPI, assessmentsAPI } from '../services/api';

export default function AssessmentsListPage() {
 const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{participantsAPI.list({page:1,size:100}).then(async r=>{const list=r.data.items||[]; const all=await Promise.all(list.map(p=>assessmentsAPI.getForParticipant(p.id).catch(()=>({data:[]})))); const mapped=[]; all.forEach((x,i)=>(x.data||[]).forEach(a=>mapped.push({...a,participant:list[i]}))); setRows(mapped.sort((a,b)=>new Date(b.assessment_date)-new Date(a.assessment_date)))}).finally(()=>setLoading(false))},[]);
 return <div className="p-6 md:p-8 max-w-7xl mx-auto"><div className="flex justify-between items-center mb-6"><div><h1 className="text-3xl font-bold">Assessments</h1><p className="text-slate-500 mt-1">Create assessments and review model explanations.</p></div><Link to="/assessments/new" className="px-4 py-2.5 rounded-xl bg-teal-700 text-white font-semibold inline-flex gap-2 items-center"><Plus size={18}/> New Assessment</Link></div>
 <div className="bg-white border rounded-2xl shadow-sm overflow-hidden">{loading?<div className="p-10 text-center text-slate-500">Loading assessments...</div>:rows.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="text-left p-4">Participant</th><th className="text-left p-4">Date</th><th className="text-left p-4">Risk</th><th className="text-left p-4">Probability</th><th className="p-4"></th></tr></thead><tbody className="divide-y">{rows.map(a=><tr key={a.id}><td className="p-4 font-semibold">{a.participant?.first_name} {a.participant?.last_name}<span className="block text-xs text-slate-400">{a.participant?.participant_id}</span></td><td className="p-4">{new Date(a.assessment_date).toLocaleString()}</td><td className="p-4"><span className="px-2.5 py-1 rounded-full text-xs font-bold bg-slate-100">{a.risk_level||'Pending'}</span></td><td className="p-4">{a.recidivism_probability==null?'—':`${(a.recidivism_probability*100).toFixed(1)}%`}</td><td className="p-4 text-right"><Link to={`/assessments/${a.id}`} className="text-teal-700 font-semibold inline-flex gap-1 items-center"><Eye size={16}/> View</Link></td></tr>)}</tbody></table></div>:<div className="p-12 text-center"><ClipboardList className="mx-auto text-slate-300" size={40}/><p className="font-semibold mt-3">No assessments yet</p><Link to="/assessments/new" className="inline-flex mt-4 px-4 py-2 bg-teal-700 text-white rounded-lg">Start one</Link></div>}</div></div>
}
