import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { interventionsAPI, participantsAPI } from '../services/api';
import toast from 'react-hot-toast';
import { Plus } from 'lucide-react';

export default function InterventionsPage() {
 const [params]=useSearchParams(); const initialParticipant=params.get('participant')||'';
 const [participants,setParticipants]=useState([]); const [participantId,setParticipantId]=useState(initialParticipant); const [plans,setPlans]=useState([]); const [form,setForm]=useState({title:'',description:'',priority:'Medium',status:'SUGGESTED',notes:''}); const [loading,setLoading]=useState(false);
 useEffect(()=>{participantsAPI.list({page:1,size:100}).then(r=>setParticipants(r.data.items||[]));},[]);
 const load=()=>participantId&&interventionsAPI.getForParticipant(participantId).then(r=>setPlans(r.data||[])).catch(()=>{});
 useEffect(()=>{load()},[participantId]);
 const create=async()=>{if(!participantId||!form.title.trim())return toast.error('Select a participant and enter a title');setLoading(true);try{await interventionsAPI.create(participantId,form);toast.success('Intervention plan created');setForm({title:'',description:'',priority:'Medium',status:'SUGGESTED',notes:''});load()}catch(e){toast.error(e.response?.data?.detail||'Could not create intervention')}finally{setLoading(false)}};
 return <div className="p-6 md:p-8 max-w-7xl mx-auto"><div className="mb-6"><h1 className="text-3xl font-bold">Intervention Plans</h1><p className="text-slate-500 mt-1">Create and track professional intervention plans.</p></div>
 <div className="grid lg:grid-cols-3 gap-5"><section className="bg-white border rounded-2xl p-5 shadow-sm"><h2 className="font-bold">Create Plan</h2><select value={participantId} onChange={e=>setParticipantId(e.target.value)} className="w-full mt-4 border rounded-lg p-2.5"><option value="">Select participant</option>{participants.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name} — {p.participant_id}</option>)}</select><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Plan title" className="w-full mt-3 border rounded-lg p-2.5"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description" rows="4" className="w-full mt-3 border rounded-lg p-2.5"/><div className="grid grid-cols-2 gap-3 mt-3"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className="border rounded-lg p-2.5"><option>Low</option><option>Medium</option><option>High</option></select><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="border rounded-lg p-2.5"><option>SUGGESTED</option><option>UNDER_REVIEW</option><option>ACCEPTED</option><option>IN_PROGRESS</option><option>COMPLETED</option><option>REJECTED</option></select></div><button disabled={loading} onClick={create} className="mt-4 w-full py-2.5 bg-teal-700 text-white rounded-lg font-semibold inline-flex justify-center gap-2"><Plus size={17}/>{loading?'Saving...':'Create Plan'}</button></section>
 <section className="lg:col-span-2 bg-white border rounded-2xl shadow-sm overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold">Plans for selected participant</h2></div>{!participantId?<div className="p-12 text-center text-slate-500">Select a participant to view their plans.</div>:plans.length?<div className="divide-y">{plans.map(p=><div key={p.id} className="p-5"><div className="flex justify-between gap-3"><div><h3 className="font-bold">{p.title}</h3><p className="text-sm text-slate-500 mt-1">{p.description||'No description'}</p></div><span className="px-2.5 py-1 rounded-full text-xs font-bold bg-teal-50 text-teal-700">{p.status}</span></div></div>)}</div>:<div className="p-12 text-center text-slate-500">No plans yet.</div>}</section></div></div>
}
